### ISSUE TITLE
[FEATURE] PostgreSQL

### ISSUE THREAD

**Issue by ghost** [MasterKrepta/AccountLogin#1]
Hi @MasterKrepta,

Instead of using `.txt` files to store your data why not use [PostgreSQL](https://www.postgresql.org/)?

**Comment by MasterKrepta** [comment]
Hi @nicotravassos. This was a quick and dirty test project. I changed it up for The AccountLogin_WPF project and used SQLite for the data storage.

**Comment by ghost** [comment]
Oh I see I still think the console idea is awesome 😎

**Comment by ghost** [comment]
Hi @MasterKrepta.

If you were to continue building on to this app I recommend using this library [CommandLineUtils](https://github.com/natemcmaster/CommandLineUtils) for your CLI.

Here is a [application](https://github.com/peacecwz/azure-storage-cli/tree/master/src/AzureStorageCLI) which is using this library maybe you can use this as a template.
